import urllib3
from bs4 import BeautifulSoup
import re

def print_all_ministries():
    url = 'https://www.usip.org/publications/2008/03/foreign-affairs-ministries-web'
    https = urllib3.PoolManager()
    data = https.request('GET', url).data
    soup = BeautifulSoup(data, features='lxml').find(class_='wysiwyg')
    soup = soup.find_all('a')
    ministries = []
    for s in soup:
        link = s.get("href")
        if link is not None and '#' not in link:
            p = re.compile('\(.+\)', re.IGNORECASE)
            country = re.search(p, s.get_text()).group(0)[1:-1]
            ministries.append((s.get("href"), country))
    print('[', end='')
    for m in ministries:
        print(m, ',', sep='')
    return

ministries = [('http://www.mfa.gov.af/', 'Afghanistan'),
('http://www.mfa.gov.al/web/Ministry_of_Foreign_Affairs_of_Albania_1_2.php', 'Albania'),
('http://193.194.78.233/ma_fr/', 'Algeria'),
('http://www.andorra.be/en/index.htm', 'Andorra'),
('http://www.mirex.gv.ao/', 'Angola'),
('http://www.mrecic.gov.ar/', 'Argentina'),
('http://www.armeniaforeignministry.com', 'Armenia'),
('http://www.dfat.gov.au/', 'Australia'),
('http://www.bmaa.gv.at/view.php3?r_id=1&LNG=en&version=', 'Austria'),
('http://www.mfa.gov.az/eng/', 'Azerbaijan'),
('http://www.mfabahamas.org/', 'Bahamas'),
('http://www.mofa.gov.bh/', 'Bahrain'),
('http://www.mofa.gov.bd/', 'Bangladesh'),
('http://www.foreign.gov.bb/', 'Barbados'),
('http://www.mfa.gov.by/en/', 'Belarus'),
('http://www.diplobel.fgov.be/default_en.htm', 'Belgium'),
('http://www.mfa.gov.bz/', 'Belize'),
('http://www.rree.gov.bo/', 'Bolivia'),
('http://www.mvp.gov.ba/', 'Bosnia and Herzegovina'),
('http://www.gov.bw/government/ministry_of_foreign_affairs.html', 'Botswanna'),
('http://www.mre.gov.br/', 'Brazil'),
('http://www.mfa.gov.bn/', 'Brunei Darussalam'),
('http://www.mfa.government.bg/', 'Bulgaria'),
('http://www.mae.gov.bf', 'Burkina Faso'),
('http://www.mfaic.gov.kh/', 'Cambodia'),
('http://www.dfait-maeci.gc.ca/', 'Canada'),
('http://www.minrel.cl/', 'Chile'),
('http://www.fmprc.gov.cn/', "China, People's Republic"),
('http://www.minrelext.gov.co/', 'Colombia'),
('http://www.rree.go.cr/', 'Costa Rica'),
('http://www.mvp.hr/index.html', 'Croatia'),
('http://www.cubaminrex.cu/', 'Cuba'),
('http://www.mfa.gov.cy/', 'Cyprus, Republic of'),
('http://www.mzv.cz/', 'Czech Republic'),
('http://www.um.dk/en', 'Denmark'),
('http://www.serex.gov.do/', 'Dominican Republic'),
('http://www.mmrree.gov.ec/', 'Ecuador'),
('http://www.mfa.gov.eg/', 'Egypt'),
('http://www.rree.gob.sv/site/index.html', 'El Salvador'),
('http://www.vm.ee/', 'Estonia'),
('http://www.mfa.gov.et/', 'Ethiopia'),
('http://www.fsmgov.org/ovmis.html', 'Federated States of Micronesia'),
('http://www.foreignaffairs.gov.fj/', 'Fiji'),
('http://formin.finland.fi/english/', 'Finland'),
('http://www.diplomatie.gouv.fr', 'France'),
('http://www.mfa.gov.ge/', 'Georgia'),
('http://www.auswaertiges-amt.de/www/en/index_html', 'Germany'),
('http://www.ghana.gov.gh/governing/ministries/governance/foreign.php', 'Ghana'),
('http://www.mfa.gr/', 'Greece'),
('http://www.minex.gob.gt/', 'Guatemala'),
('http://www.sdnp.org.gy/minfor/', 'Guyana'),
('http://www.sre.hn/', 'Honduras'),
('http://www.mfa.gov.hu/kum/en/bal/', 'Hungary'),
('http://www.mfa.is/', 'Iceland'),
('http://meaindia.nic.in/', 'India'),
('http://www.deplu.go.id/', 'Indonesia'),
('http://www.mfa.gov.ir', 'Iran'),
('http://www.mofa.gov.iq/index.aspx', 'Iraq'),
('http://foreignaffairs.gov.ie/', 'Ireland'),
('http://www.mfa.gov.il/mfa', 'Israel'),
('http://www.esteri.it/eng/index.asp?', 'Italy'),
('http://www.mfaft.gov.jm', 'Jamaica'),
('http://www.mofa.go.jp/', 'Japan'),
('http://www.mfa.gov.jo/', 'Jordan'),
('http://www.mfa.kz/', 'Kazakhstan'),
('http://www.mfa.go.ke/', 'Kenya'),
('http://www.mfa.kg/', 'Kyrgyzstan'),
('http://www.mofa.gov.la', 'Laos'),
('http://www.am.gov.lv/en/', 'Latvia'),
('http://www.emigrants.gov.lb/', 'Lebanon'),
('http://www.lesotho.gov.ls/foreign/', 'Lesotho'),
('http://www.mofa.gov.lr/', 'Liberia'),
('http://www.foreign.gov.ly/online/', 'Libya'),
('http://www.urm.lt/', 'Lithuania'),
('http://www.mae.lu/MAE.taf', 'Luxembourg'),
('http://www.mfa.gov.mk/default.aspx?ItemID=282', 'Macedonia'),
('http://www.madagascar-diplomatie.net/', 'Madagascar'),
('http://www.kln.gov.my/', 'Malaysia'),
('http://www.foreign.gov.mt', 'Malta'),
('http://www.gov.mu/portal/site/mfasite', 'Mauritius'),
('http://www.sre.gob.mx', 'Mexico'),
('http://www.mfa.md/En/', 'Moldova'),
('http://www.relext.gouv.mc/315/wwwnew.nsf/Home', 'Monaco'),
('http://www.mfa.gov.mn/', 'Mongolia'),
('http://www.vlada.cg.yu/eng/mininos/', 'Montenegro'),
('http://www.maec.gov.ma', 'Morocco'),
('http://www.micoa.gov.mz/', 'Mozambique'),
('http://www.mofa.gov.mm/', 'Myanmar'),
('http://www.mfa.gov.na/', 'Namibia'),
('http://www.mofa.gov.np/', 'Nepal'),
('http://www.minbuza.nl/en/home', 'Netherlands'),
('http://www.mft.govt.nz/', 'New Zealand'),
('http://www.cancilleria.gob.ni/', 'Nicaragua'),
('http://www.nigeria.gov.ng/ministries/foreign.htm', 'Nigeria'),
('http://www.regjeringen.no/en/dep/ud.html?id=833', 'Norway'),
('http://www.mofa.gov.om/', 'Oman'),
('http://www.mofa.gov.pk/', 'Pakistan'),
('http://www.mofa.gov.ps/', 'Palestinian National Authority'),
('http://www.mire.gob.pa/', 'Panama'),
('http://www.mre.gov.py/', 'Paraguay'),
('http://www.rree.gob.pe/portal/mre.nsf/Index?OpenForm', 'Peru'),
('http://www.dfa.gov.ph/', 'Philippines'),
('http://www.mfa.gov.pl/', 'Poland'),
('http://www.min-nestrangeiros.pt/mne/', 'Portugal'),
('http://www.mofa.gov.qa/', 'Qatar'),
('http://www.mae.ro/', 'Romania'),
('http://www.mid.ru/', 'Russia'),
('http://www.minaffet.gov.rw/', 'Rwanda'),
('http://www.mofa.gov.kn/', 'Saint Kitts and Nevis'),
('http://www.stlucia.gov.lc/index.html', 'Saint Lucia'),
('http://www.esteri.sm/', 'San Marino'),
('http://www.mofa.gov.sa/', 'Saudi Arabia'),
('http://www.diplomatie.gouv.sn/', 'Senegal'),
('http://www.mfa.gov.yu/', 'Serbia'),
('http://www.mfa.gov.sc/', 'Seychelles'),
('http://www.mfa.gov.sg/internet/', 'Singapore'),
('http://www.foreign.gov.sk/', 'Slovakia'),
('http://www.mzz.gov.si', 'Slovenia'),
('http://www.dfa.gov.za/department/index.html', 'South Africa'),
('http://www.mofat.go.kr/english/main/index.jsp?lang=eng', 'South Korea'),
('http://www.mae.es/', 'Spain'),
('http://www.slmfa.gov.lk/', 'Sri Lanka'),
('http://www.sudanmfa.com/', 'Sudan'),
('http://www.gov.sz/home.asp?pid=60', 'Swaziland'),
('http://www.ud.se/', 'Sweden'),
('http://www.eda.admin.ch/eda/en/home.html', 'Switzerland'),
('http://www.mofa.gov.tw/', 'Taiwan'),
('http://www.tanzania.go.tz/foreign.htm', 'Tanzania'),
('http://www.mfa.go.th/', 'Thailand'),
('http://www.mfac.gov.tp/', 'Timor-Leste'),
('http://www.ministeres.tn/html/ministeres/etrangeres.html', 'Tunisia'),
('http://www.mfa.gov.tr/default.en.mfa', 'Turkey'),
('http://www.mofa.go.ug/', 'Uganda'),
('http://www.mfa.gov.ua', 'Ukraine'),
('http://www.fco.gov.uk/servlet/Front?pagename=OpenMarket/Xcelerate/ShowPage&c=Page&cid=1007029390554', 'United Kingdom'),
('http://www.state.gov/', 'United States'),
('http://www.mrree.gub.uy/mrree/index.htm', 'Uruguay'),
('http://www.mfa.uz/', 'Uzbekistan'),
('http://www.vatican.va/roman_curia/secretariat_state/', 'The Vatican'),
('http://www.mre.gov.ve/', 'Venezuela'),
('http://www.mofa.gov.vn/en', 'Vietnam'),
('http://web.yemen.net.ye/egov/foreign-english/index.html', 'Yemen'),
('http://www.zimfa.gov.zw/zfsi/index.htm', 'Zimbabwe')]